name: Publish Package to NPM
on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: 'korhanozbek'
          always-auth: true
      - run: npm publish --loglevel verbose
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}